language: python
python:
  - "3.6"

install:
  - pip install poetry
  - poetry export --dev -f requirements.txt > requirements.txt
  - pip install -r requirements.txt

script:
  - python -m pytest
  - pylint -f parseable --errors-only --rcfile setup.cfg digitalocean_firewalls_ip_changer
